server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          default-label: feature/springBoot
          uri: https://github.com/angelmillan123/courseSB
          search-paths: config-data  application:
    name: config-service        